<?php
/**
 * @file
 * Google Analytics Event Tracking Module API Example.
 *
 * Shows a quick and dirty example of how to integrate the Google Analytics
 * Event Tracking Module into an user's module.
 */

/**
 * Implements hook_google_analytics_et_settings_info().
 */
function ddg_ga_contact_google_analytics_et_settings_info() {
  $settings = array();

  $settings['debug'] = TRUE;

  return $settings;
}

/**
 * Implements hook_google_analytics_et_api().
 */
function ddg_ga_contact_google_analytics_et_api() {
  return _ddg_ga_contact_set_selectors_array();
}

/**
 * 
 */
function _ddg_ga_contact_set_selectors_array() {
  $selectors = array();

  $selectors = array(
    array(
      'event' => 'mousedown',
      'selector' => '#edit-webform-ajax-submit-4',
      'category' => 'webform submission',
      'action' => 'click',
      'label' => 'contact submission',
      'value' => 0,
      'noninteraction' => TRUE,
    )
  );

  return $selectors;
}
